Icespine_Out      E收扇子
ShowUp      上场
Upstairs      上楼
FallingAnthem_AS_1      下落攻击_AS_1
FallingAnthem_AS_2      下落攻击_AS_2
FallingAnthem_Loop      下落攻击_Loop
FallingAnthem_Loop_Low      下落攻击_Loop_Low
ChannelBS      伸胳膊
ChannelLoop      伸胳膊_AS
RunToIdle      停止奔跑
Sprint      冲刺
SprintBS      冲刺BS
Icespine      凌华的E技能
Akimbo02AS      单手叉腰_AS
Akimbo02BS      单手叉腰_BS
Akimbo02Loop      单手叉腰_Loop
ActivitySkill_ElectricCoreFly      原地风之翼
Hit_H      受击_H
Hit_L      受击_L
Hit_Throw_Ground      受击_地板溅射
Hit_Throw      受击_砸中
Hit_ThrowAir      受击_空中砸中
Struggle      受击_翻滚
CrouchDrop      召唤上升气流
StandbyPutawayOver      召唤武器
SitLoop      坐_Loop
SitUp      坐_起来
SitDown      坐下
FrozenWindmill      大招动画
FrozenWindmill_AS      大招动画_AS
RunToWalk      奔跑到步行
FlyStart      开始飞
Standby      待机
StandbyShow_01      待机动画_01
StandbyShow_02      待机动画_02
StandbyVoice      待机语音
Think01AS      思考01_AS
Think01BS      思考01_BS
Think01Loop      思考01_Loop
SprintToIdle      怠速冲刺
FallDie      摔死
FallDie_AS      摔死_AS
ClimbDownToGround      攀爬到地面
ClimbMove1      攀爬移动
ClimbJump      攀登跳跃
StandbyPutaway      收武器
Attack01      攻击01
Attack02      攻击02
Attack03      攻击03
Attack04      攻击04
Attack05      攻击05
SkiffNormal      正常情况
NormalDie      正常死亡
WalkToRun      步行到跑步
WalkToIdle      步行至停顿
JumpForWalk      步行跳跃
StandbyWeapon      武器待机
LiquidStrike_MoveStandby      液体模式
LiquidStrike_FatalMove      液体模式_FatalMove
LiquidStrike_Move      液体模式_Move
SwimDie      淹死
SwimIdle      游泳
SitDown      游泳冲刺
SwimJumpDrop      游泳跳下
SwimJumpToWater      游泳跳到水里
SwimJump      游泳跳跃
SwimMove      游泳运动
Standby2ClimbA      爬墙待机A
Standby2ClimbB      爬墙待机B
ClimbIdle      爬行待机
FallToGroundRunHard      翻滚
DropDown      落地
FallOnGroundLit      落地lit
FallToGroundRun      落地跑
HitGroundDie      被砸死在地上
Walk      走
Run      跑
JumpForRun      跑步跳跃
JumpUpWallReady      跳上墙准备
JumpUpWallForStandby      跳上墙待机
JumpOffWall      跳出墙面
Jump      跳跃
JumpForSprint      跳跃冲刺
CrouchToStandby      蹲下待机
CrouchMove      蹲下移动
CrouchRoll      蹲下翻滚
CrouchIdle      蹲下闲置
TurnDir      转移方向
ExtraAttack      重击
ExtraAttack_AS      重击_AS
PlayMusic_Qin_AS      镜花之琴_AS
PlayMusic_Qin_BS      镜花之琴_BS
PlayMusic_Qin_Loop      镜花之琴_Loop
PlayMusic_Lyre_AS      风物之琴_AS
PlayMusic_Lyre_BS      风物之琴_BS
PlayMusic_Lyre_Loop      风物之琴_Loop
Fly      飞行
SitBLoop      高脚凳坐_Loop
SitBUp      高脚凳坐_起来
SitBDown      高脚凳坐下
